/** Concise tooltips for every technical parameter (keyed by control id). */
export const TOOLTIPS: Record<string, string> = {
  signalType: 'Signal family. Each family is a template over the same general model; every parameter stays editable.',
  amplitude: 'Peak amplitude A of the waveform. Normalized, volts across the load set in Power & energy, or V/m for a free-space field. Scales the spectrum without changing its shape.',
  carrierEnabled: 'Multiply the envelope by a sinusoidal carrier. Without a carrier the pulse is a baseband signal centered at DC.',
  f0: 'Carrier frequency f₀. Translates the envelope spectrum to ±f₀; it does not set the envelope bandwidth.',
  phase: 'Initial carrier phase φ₀ at the pulse center (or t = 0 for a continuous wave). Changes spectral phase, not |X(f)|.',
  pulseEnabled: 'Gate the signal with a finite envelope a(t). A finite duration always implies a spread of frequencies.',
  envelope: 'Envelope shape a(t). Smoother shapes concentrate energy (lower sidelobes); abrupt edges spread it to high frequencies.',
  pulseWidth:
    'Pulse duration τ. Rect/trapezoid: 50 % width. Gaussian family: FWHM of the Gaussian. Hann/Hamming/Blackman/Tukey: full support. Bandwidth scales as 1/τ.',
  pulseCenter: 'Time of the pulse (train) center. Auto places it in the middle of the observation window.',
  edges: 'Replace the ideal discontinuity with finite ramps. Pulse width (50 % points) is unchanged.',
  edgeShape: 'Linear ramps keep a kink (spectrum ∝ 1/f² far out); raised-cosine ramps are smooth (faster decay).',
  riseTime: 'Time required for the pulse edge to transition between 10 % and 90 % of the amplitude. Faster edges produce stronger high-frequency components.',
  fallTime: 'Time for the trailing edge to fall from 90 % to 10 %. Independent from the rise time.',
  tukeyAlpha: 'Fraction of the Tukey (raised-cosine) window that is tapered. α = 0 → rectangular, α = 1 → Hann.',
  trainEnabled: 'Repeat the pulse at a fixed interval T_r = 1/PRF.',
  prf: 'Pulse repetition frequency. Determines how frequently pulses repeat. For a coherent periodic train, spectral lines appear approximately PRF apart.',
  pulseCount: 'Number of pulses N. Longer trains (T_burst = N/PRF) produce narrower spectral lines, ≈ 1/T_burst.',
  dutyCycle: 'Fraction of the repetition interval occupied by the pulse: τ·PRF. Editing it changes τ.',
  ampVariation: 'Deterministic pulse-to-pulse amplitude pattern: linear ramp or alternating levels.',
  coherence: 'Stability of the phase relationship between successive pulses.',
  carrierReference:
    'Gated CW: the carrier runs continuously and pulses are windows on it (lines at f₀ + k·PRF). Pulse-locked: each pulse is an identical copy (lines at k·PRF).',
  phaseIncrement: 'Deterministic phase step Δφ added to each successive pulse: φₙ = φ₀ + nΔφ. Shifts the comb by Δφ/(2π)·PRF.',
  phaseNoise: 'RMS of Gaussian pulse-to-pulse phase noise εₙ ~ N(0, σφ²).',
  timingJitter: 'Random deviation of the pulse times: tₙ = nT_r + Δtₙ. Smears comb lines, increasingly at higher frequencies.',
  timingMode: 'Random: Gaussian jitter. Periodic: sinusoidal jitter, which creates discrete sidebands instead of a smeared floor.',
  timingPeriod: 'Period (in pulses) of the sinusoidal jitter pattern.',
  amplitudeJitter: 'Random pulse-to-pulse amplitude variation: Aₙ = A(1 + εₙ).',
  frequencyJitter: 'Random pulse-to-pulse carrier variation: f₀,ₙ = f₀ + Δfₙ.',
  seed: 'Seed of the deterministic random generator. The same seed reproduces the same realization.',
  chirp: 'Linear frequency modulation: f_inst(t) = f_c + k·(t − tₙ). The swept range sets the occupied bandwidth, B ≈ |k|·T.',
  chirpStart: 'Instantaneous frequency at the start of the pulse (or record).',
  chirpEnd: 'Instantaneous frequency at the end of the pulse (or record).',
  am: 'Amplitude modulation m(t) = 1 + μ·cos(2πf_m t). Adds sidebands at ±f_m around every spectral component.',
  amDepth: 'Modulation depth μ (0 … 1).',
  amFreq: 'Modulating frequency f_m.',
  noise: 'Additive white Gaussian noise. Raises a flat floor in the PSD; use the Welch estimator to average it.',
  noiseRms: 'RMS value of the additive noise.',
  samplingMode: 'Auto chooses fₛ and N from the waveform model so the significant spectrum lies within Nyquist. Manual lets you undersample on purpose.',
  fs: 'Sampling frequency fₛ. Sets the Nyquist frequency f_N = fₛ/2. It does not change the physical spectrum.',
  sampleCount: 'Number of samples N in the record. Together with fₛ it sets the observation T_obs = N/fₛ.',
  observation: 'Observation duration T_obs = N/fₛ. The DFT bin spacing is 1/T_obs.',
  quantization: 'Round samples to a finite number of ADC levels. Adds quantization noise (≈ 6.02·bits + 1.76 dB SQNR for a full-scale sine).',
  bits: 'ADC resolution in bits (2^bits levels across the full scale).',
  aliasingDemo: 'Show the continuous physical waveform and its spectrum next to the sampled representation.',
  display: 'Quantity plotted versus frequency: magnitude |X|, normalized magnitude, dB re. peak, power |X|², or power spectral density.',
  scaling:
    'Fourier-transform estimate (V/Hz): Δt·DFT, physical units for pulses. Amplitude spectrum (V): DFT/Σw, reads tone amplitudes directly.',
  sided: 'One-sided: 0 … fₛ/2 (real signals have conjugate-symmetric spectra). Two-sided: −fₛ/2 … +fₛ/2 including the mathematically present negative frequencies.',
  centered: 'Centered (fftshift): −fₛ/2 … fₛ/2. Uncentered: raw DFT order 0 … fₛ, showing the periodicity of the DFT.',
  window: 'Analysis window applied to the record before the DFT. Trades main-lobe width against sidelobe level (leakage).',
  zeroPad: 'Append zeros before the DFT. Interpolates the spectrum (smaller bin spacing) but does not add information or resolution.',
  dbFloor: 'Lower limit of dB displays. Lower floors reveal the theoretical spectral tails.',
  freqRange: 'Visible frequency span. "Fit" frames the current envelope; it does not change automatically, so width changes stay visible.',
  singlePulse: 'Overlay the spectrum of one clean pulse ×N (coherent line envelope) and ×√N (average incoherent level).',
  rawBins: 'Mark the un-padded DFT samples. The zero-padded curve passes exactly through them.',
  bandMarkers: 'Shade the measured −3 dB and 99 % occupied bands.',
  fftSelection: 'Compute the spectrum of the cursor interval t₁ … t₂ only. Shorter observations broaden spectral features.',
  estimator: 'Periodogram: single DFT of the record. Welch: average of overlapping segment periodograms (lower variance, coarser resolution).',
  spectrumKind: 'Baseband: bandwidths measured from DC. Bandpass: measured between lower and upper edges around the spectral peak.',
  phaseReference: 'Reference time for the phase: the pulse center removes the linear phase of the pulse delay.',
  stftWindow: 'STFT window length L. Long windows: fine Δf, coarse Δt. Short windows: fine Δt, coarse Δf.',
  stftOverlap: 'Overlap between successive frames. More overlap → smoother time axis, more computation (not more resolution).',
  stftNfft: 'FFT length per frame (zero padding of each frame). Interpolates along frequency only.',
  dbRange: 'Displayed dynamic range below the maximum.',
  wavelet: 'Mother wavelet. Morlet: Gaussian-windowed complex exponential (good frequency localization). Mexican hat: real, better time localization.',
  omega0: 'Morlet central frequency parameter ω₀: more oscillations under the Gaussian envelope. Larger ω₀ gives better frequency and worse time resolution at every scale.',
  scales: 'Number of logarithmically spaced analysis frequencies (scales).',
  cwtRange: 'Frequency range analyzed by the CWT.',
  fftResolution: 'Frequency-bin spacing fₛ/N. It is not necessarily the physical bandwidth or resolving capability of the complete measurement.',
  cursors: 'Draggable measurement cursors in both plots: Δt, Δf and their product.',
};
